---
services:
    _defaults:
        autowire: true

    _instanceof:
        Flutchman\eZCommandsHelper\Core\Command:
            tags: [flutchman.ezcommands.command]

    # Explicit command definition
    Flutchman\eZCommandsHelper\Command\All: ~
    Flutchman\eZCommandsHelper\Command\Assets: ~
    Flutchman\eZCommandsHelper\Command\BundleAssets: ~
    Flutchman\eZCommandsHelper\Command\CacheClear: ~
    Flutchman\eZCommandsHelper\Command\Cleanup: ~
    Flutchman\eZCommandsHelper\Command\Rollback: ~
    Flutchman\eZCommandsHelper\Command\SymfonyRun: ~
    Flutchman\eZCommandsHelper\Command\Translations: ~

    # Self
    Flutchman\eZCommandsHelper\Command\SelfUpdate:
        calls:
            - [setParameters, [ {env: "%app_env%", url: "%phar_url%", version: "%phar_version%"}] ]

