---
services:
    _defaults:
        autowire: true

    _instanceof:
        Flutchman\eZCommandsHelper\Core\Command:
            tags: [flutchman.ezcommands.command]

    Flutchman\eZCommandsHelper\Command\Rollback: ~
    Flutchman\eZCommandsHelper\Command\SymfonyRun: ~

    # Self
    Flutchman\eZCommandsHelper\Command\SelfUpdate:
        calls:
            - [setParameters, [ {env: "%app_env%", url: "%phar_url%", version: "%phar_version%"}] ]

