---
parameters:
    phar_url: 'https://github.com/flutchman/eZCommandsHelper/tree/master/docs/ez-cmd.phar'
    phar_version: 'https://github.com/flutchman/eZCommandsHelper/tree/master/docs/ez-cmd.phar.version'

services:
    _defaults:
        autowire: true

    Flutchman\eZCommandsHelper\Listener\ApplicationUpdate:
        arguments:
            - {env: "%app_env%", dir: "%app_dir%", url: "%phar_url%", version: "%phar_version%"}
            - "@project_configuration"
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    Flutchman\eZCommandsHelper\Listener\CommandException:
        tags:
            - { name: kernel.event_listener, event: console.error, method: onExceptionAction }

    Flutchman\eZCommandsHelper\Listener\CommandStart:
        tags:
            - { name: kernel.event_listener, event: console.command, method: onCommandAction }

    Flutchman\eZCommandsHelper\Listener\CommandTerminate:
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onTerminateAction }
